// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * AMD shim for FullCalendar v6.1.21 (self-hosted for ATTT airgapped compliance).
 *
 * The pre-built AMD bundle is at amd/build/fullcalendar.min.js, generated from
 * amd/lib/fullcalendar-6.1.21/index.global.min.js (FullCalendar Standard Bundle).
 *
 * Usage from other AMD modules:
 *   define(['local_vbs_schedule/fullcalendar'], function(FullCalendar) {
 *       var calendar = new FullCalendar.Calendar(el, { ... });
 *   });
 *
 * @module     local_vbs_schedule/fullcalendar
 * @copyright  2026 VBS Đào tạo
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 *
 * FullCalendar Standard Bundle v6.1.21
 * Copyright (c) 2024 Adam Shaw
 * License: https://fullcalendar.io/docs/initialize-globals (MIT)
 * Source: amd/lib/fullcalendar-6.1.21/index.global.min.js
 *
 * NOTE: Do NOT load FullCalendar from a CDN — this plugin must work in
 * airgapped (ATTT) environments. Always serve from this self-hosted copy.
 * See VBS-420 for compliance rationale.
 */

// The production bundle (amd/build/fullcalendar.min.js) is generated by
// wrapping amd/lib/fullcalendar-6.1.21/index.global.min.js inside define().
// This source file documents the intent; the actual AMD module is the build file.
define([], function() {
    'use strict';

    // Delegate to the pre-built bundle which exposes the FullCalendar namespace.
    // This define() stub is the source; the build file contains the full library code.
    // eslint-disable-next-line no-undef
    return typeof FullCalendar !== 'undefined' ? FullCalendar : null;
});
